### ISSUE TITLE
Move gibbs to communications

### ISSUE THREAD

**Issue by ojaoweir** [pumpumba/pumpumba.github.io#10]

**Comment by ojaoweir** [comment]
Remove Katarina
Move Oscar to management

**Comment by ojaoweir** [comment]
Add technical writer to sofie
Remove line manager for oscar

**Comment by ojaoweir** [comment]
Add "/Front-End" to Jonatan, Marcus, Jesper

**Comment by codebyjonas** [comment]
Fixed
